version: "3.8"

services:
  replica:
    build: .
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - TARGET_ORIGIN
      - MY_ORIGIN
      - REPLACEMENTS
    restart: unless-stopped
